language: generic
sudo : required
services:
    - docker

env:
    global:
        - GIT_SHA=$(git rev-parse HEAD)  
        - CLOUDSDK_CORE_DISABLE_PROMPTS=1  

before_install:
    - openssl aes-256-cbc -K $encrypted_9f3b5599b056_key -iv $encrypted_9f3b5599b056_iv -in service-account.json.enc -out service-account.json -d
    - curl https://sdk.cloud.google.com | bash > /dev/null;
    - source $HOME/google-cloud-sdk/path.bash.inc
    - gcloud components update kubectl
    - gcloud auth activate-service-account --key-file service-account.json
    - gcloud config set project multi-k8s-312904
    - gcloud config set compute/zone asia-southeast2-a
    - gcloud container clusters get-credentials multi-k8s
    #- sudo gcloud services enable containerregistry.googleapis.com
    - gcloud auth configure-docker
   # - echo "$GCR_DOCKER_PASSWORD" | docker login -u "$GCR_DOCKER_USERNAME" --password-stdin
    - docker build -t asia.gcr.io/multi-k8s-312904/multi-client-test -f ./client/Dockerfile.dev ./client
    - docker push asia.gcr.io/multi-k8s-312904/multi-client-test

script:
    - docker run -e CI=true asia.gcr.io/multi-k8s-312904/multi-client-test npm test

# deploy: 
#     provider: script
#     script: bash ./deploy.sh
#     on:
#         branch: master
