apiVersion: cert-manager.io/v1
 
kind: Certificate
metadata:
  name: rifqi-web-id-tls
spec:
  secretName: rifqi-web-id
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: rifqi.web.id
  dnsNames:
    - rifqi.web.id
    - www.rifqi.web.id